# Generated by Django 2.2.2 on 2019-06-19 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(help_text='Author Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='book_number',
            field=models.IntegerField(help_text='Book author', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='birth'),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(help_text='book author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique id', primary_key=True, serialize=False),
        ),
    ]
