# Generated by Django 2.2.2 on 2019-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190619_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_number',
            field=models.IntegerField(help_text='Book number', null=True),
        ),
    ]
