# Generated by Django 2.2.2 on 2019-06-20 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190619_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique id', primary_key=True, serialize=False),
        ),
    ]
