# Generated by Django 2.2.2 on 2019-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190620_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(help_text='enter your name', max_length=100, null=True)),
                ('book_needed', models.CharField(help_text='enter the name of the book', max_length=100, null=True)),
                ('book_issue', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('book_return', models.DateField(blank=True, null=True, verbose_name='birth')),
            ],
        ),
    ]
